# Generated by Django 3.2.6 on 2021-12-07 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps_tenantRecords', '0002_scexpense_vendor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scexpense',
            name='Vendor',
        ),
    ]
