# Generated by Django 3.2.6 on 2021-12-07 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps_tenantRecords', '0004_scexpense_vendor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scexpense',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=30, null=True),
        ),
    ]
