# Generated by Django 3.2.6 on 2021-12-09 16:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tenantRecords', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('address', models.CharField(blank=True, default='', max_length=500, null=True)),
                ('bank_name', models.CharField(blank=True, default='', max_length=500, null=True)),
                ('account_number', models.CharField(blank=True, default='', max_length=500, null=True)),
                ('account_name', models.CharField(blank=True, default='', max_length=500, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='shop',
            name='percentpaid',
            field=models.FloatField(default=0),
        ),
        migrations.CreateModel(
            name='SCExpense',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(null=True, verbose_name='Expense Date')),
                ('amount', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=30, null=True)),
                ('description', models.CharField(blank=True, default='', max_length=500, null=True)),
                ('status', models.CharField(blank=True, choices=[('paid', 'paid'), ('unpaid', 'unpaid')], default='', max_length=500, null=True)),
                ('shop', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sc_expense', to='tenantRecords.shop')),
                ('vendor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sc_expense', to='tenantRecords.vendor')),
            ],
        ),
    ]
