name: Django CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:   
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: deploy to Opalstack
        uses: appleboy/ssh-action@master
        with:
          host: ${{secrets.SSH_HOST}}
          password: ${{ secrets.PASSWORD }}
          username: ${{secrets.SSH_USERNAME}}
          
          script: |
            cd apps/amaro_dashboard
            source venv/bin/activate
            cd amaro_dashboard
            git stash
            git pull git@github.com:girlProg/amaro_dashboard.git
            pip3 install -r requirements.txt
            python manage.py migrate
            deactivate
            cd ..
            ./stop
            ./start
            echo 'Deployment successful'
            
            
